### ISSUE TITLE
SAWilsonBalding can get stuck

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/sampled-ancestors#4]
Under special circumstances, there is no node available for the SAWilsonBalding move, and the proposal methods can get stuck in a loop. A possible solution is to give up (and return Double.NEGATIVE_INFINITY) after say 100 attempts to find a candidate node.

**Comment by alexeid** [comment]
If the move can’t get to these places (i.e. the topology is only arrived at by another tree operator) then you just need to reject (without any attempts at all). 

But we should be very careful that we don’t break the hastings ratio. What is the example? This condition should have been considered when developing the operator.

**Comment by jheled** [comment]
If I may elaborate on Alexie's words, I think what he means is that tree operators which follow the pattern:

while (no suitable node) :
  pick a random node.
  if node is suitable -> break
  otherwise continue.

Should not be "blindly enhanced" thus

while (no suitable node) :
  if more than X tries -> reject
  pick a random node.
  if node is suitable -> break
  otherwise continue.

but instead with something like that

while (no suitable node) :
  if more than X tries -> loop over all nodes in tree. If none is suitable -> reject
  pick a random node.
  if node is suitable -> break
  otherwise continue.

Obviously there are various ways to micro optimize the obove, but this should not be crucial. Operators following this pattern typically expect most nodes to be applicable. When not, it is better to first scan all nodes, pick valid nodes and select uniformly between them.

**Comment by tgvaughan** [comment]
I think the best solution to this problem would be to detect whether the operator is applicable to the tree right at the start, then reject if the operator is not applicable.  I had to do very similar things for the MTT WB move, although there the tricky tests are the ones guarding against choices for the first node that make choosing a valid second node impossible.

Would writing such a test be possible in this case?

**Comment by gavryushkina** [comment]
The operator does reject trees where after choosing a subtree to prune there is no possibilities to attach it too. It would be nice to see the example of the tree. I can imagine a situation where the move is possible but the probability of choosing the possible combination is very low. Like if the part of the branch where a subtree can be attached is very small compared to the total branch length or if the number of branches in the tree is huge and there is only few where it can be attached to.

**Comment by rbouckaert** [comment]
Forwarded an example from Carlo to Sasha so the problem can be replicated.
